# Database configuration
database:
  driverClass: com.mysql.cj.jdbc.Driver
  url: ${CONFIG_SERVICE_DB_URL:-jdbc:mysql://localhost:3306/db}
  user: ${CONFIG_SERVICE_DB_USER:-root}
  password: ${CONFIG_SERVICE_DB_PASSWORD:-}
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.hbm2ddl.auto: create-drop
    hibernate.format_sql: true
    hibernate.show_sql: true
  minSize: 5
  maxSize: 10

# Server configuration
server:
  applicationConnectors:
  - type: http
    port: ${CONFIG_SERVICE_API_PORT:-10443}
  adminConnectors:
  - type: http
    port: ${CONFIG_SERVICE_ADMIN_PORT:-11443}
  requestLog:
    appenders:
      - type: file
        threshold: ${logging.request.threshold}
        currentLogFilename: ${path.base}/logs/requests.log
        archivedLogFilenamePattern: ${path.base}/logs/requests-%d.log
        archive: ${logging.request.archive}
        archivedFileCount: ${logging.request.archive.filecount}
        timeZone: ${logging.request.timezone}

# Logging configuration
logging:
  level: ${logging.level}
  appenders:
    - type: file
      threshold: ${logging.level}
      currentLogFilename: ${path.base}/logs/service.log
      archivedLogFilenamePattern: ${path.base}/service-%d.log
      archive: ${logging.archive}
      archivedFileCount: ${logging.archive.filecount}
      timeZone: ${logging.timezone}
      logFormat: "${logging.pattern}"