# Database configuration
database:
  datasource:
    driverClass: ${db.driver.class}
    url: jdbc:postgresql://${CONFIG_SERVICE_DB_HOSTNAME:-localhost}:${CONFIG_SERVICE_DB_PORT:-3306}/${CONFIG_SERVICE_DB_NAME:-db}?reWriteBatchedInserts=true
    user: ${CONFIG_SERVICE_DB_USER:-user}
    password: ${CONFIG_SERVICE_DB_PASSWORD:-user}
    properties:
      charSet: ${db.charset}
      hibernate.dialect: ${db.hibernate.dialect}
      hibernate.hbm2ddl.auto: ${db.hibernate.hbm2ddl.auto}
      hibernate.format_sql: ${db.hibernate.sql.format}
      hibernate.show_sql: ${db.hibernate.sql.show}
      hibernate.generate_statistics: ${db.hibernate.statistics.generate}
      hibernate.connection.autocommit: ${db.hibernate.connection.autocommit}
      hibernate.jdbc.batch_size: ${db.hibernate.batch.size}
      hibernate.order_inserts: ${db.hibernate.order.inserts}
      hibernate.order_updates: ${db.hibernate.order.updates}
    minSize: ${db.pool.min}
    maxSize: ${db.pool.max}

# Server configuration
server:
  applicationConnectors:
  - type: http
    port: ${CONFIG_SERVICE_API_PORT:-8080}
  adminConnectors:
  - type: http
    port: ${CONFIG_SERVICE_ADMIN_PORT:-8090}
  requestLog:
    appenders:
      - type: file
        threshold: ${logging.request.threshold}
        currentLogFilename: ${path.base}/logs/requests.log
        archivedLogFilenamePattern: ${path.base}/logs/requests-%d.log
        archive: ${logging.request.archive}
        archivedFileCount: ${logging.request.archive.filecount}
        timeZone: ${logging.request.timezone}

# Logging configuration
logging:
  level: ${logging.level}
  appenders:
    - type: file
      threshold: ${logging.level}
      currentLogFilename: ${path.base}/logs/service.log
      archivedLogFilenamePattern: ${path.base}/service-%d.log
      archive: ${logging.archive}
      archivedFileCount: ${logging.archive.filecount}
      timeZone: ${logging.timezone}
      logFormat: "${logging.pattern}"